-- Seed: the full permission catalogue (idempotent).
-- Permission codes are a permanent public contract (see libs/contracts/permissions.ts).
INSERT INTO permissions (code, resource, action, description) VALUES
  ('tenant:manage',     'tenant',     'manage',    'Manage operator settings, plan, provisioning'),
  ('tenant:read',       'tenant',     'read',      'View operator settings'),
  ('user:manage',       'user',       'manage',    'Create/update/deactivate users'),
  ('user:read',         'user',       'read',      'View users'),
  ('role:manage',       'role',       'manage',    'Manage roles and permissions'),
  ('route:manage',      'route',      'manage',    'Manage routes'),
  ('route:read',        'route',      'read',      'View routes'),
  ('stop:manage',       'stop',       'manage',    'Manage stops/geography'),
  ('layout:manage',     'layout',     'manage',    'Manage seat layouts'),
  ('vehicle:manage',    'vehicle',    'manage',    'Manage vehicles'),
  ('vehicle:read',      'vehicle',    'read',      'View vehicles'),
  ('crew:manage',       'crew',       'manage',    'Manage crew + duty roster'),
  ('agent:read',        'agent',      'read',      'View agents + their account ledger'),
  ('agent:manage',      'agent',      'manage',    'Register/approve agents, record deposits/payments, set credit limits'),
  ('agent:portal',      'agent',      'portal',    'Agent self-service portal: own account + own bookings only'),
  ('service:manage',    'service',    'manage',    'Manage services'),
  ('service:read',      'service',    'read',      'View services'),
  ('trip:manage',       'trip',       'manage',    'Manage trips + inventory'),
  ('trip:operate',      'trip',       'operate',   'Operate trips (charting, boarding, ticket verify)'),
  ('inventory:manage',  'inventory',  'manage',    'Manage seat inventory'),
  ('fare:manage',       'fare',       'manage',    'Manage fares + pricing'),
  ('fare:read',         'fare',       'read',      'View fares'),
  ('booking:read',      'booking',    'read',      'View bookings'),
  ('booking:create',    'booking',    'create',    'Create bookings'),
  ('booking:cancel',    'booking',    'cancel',    'Cancel bookings'),
  ('booking:reschedule','booking',    'reschedule','Reschedule/amend bookings'),
  ('payment:read',      'payment',    'read',      'View payments/refunds/risk'),
  ('payment:refund',    'payment',    'refund',    'Issue refunds'),
  ('settlement:manage', 'settlement', 'manage',    'Manage settlements + invoices'),
  ('report:read',       'report',     'read',      'View reports/BI'),
  ('report:export',     'report',     'export',    'Export reports'),
  ('tracking:read',     'tracking',   'read',      'View live tracking'),
  ('platform:operators','platform',   'operators', 'Review + approve operator applications'),
  ('platform:admin',    'platform',   'admin',     'Full platform administration')
ON CONFLICT (code) DO NOTHING;
