-- =============================================================================
-- 0108_reminder_seats
--
-- The bus and crew of a trip are settled by the 4-hour reminder; picking
-- another bus before then is normal planning and sends no separate message.
-- If that bus has a different seat plan, a passenger's seat number may
-- change — so the 4-hour and 1-hour reminders now carry the seat number(s)
-- too. Untouched default wording moves to the new wording; an operator's
-- own text is kept.
-- =============================================================================

-- migrate:up

UPDATE notification_templates SET body = 'Boarding in 4h — PNR {{pnr}}, {{boardingAt}}. Pickup: {{pickup.stopName}} ({{pickup.landmark}}). Bus {{busNumber}}, seat(s) {{seats}}. Driver(s): {{driversList}}. Crew: {{attendantsList}}. Track (live from {{trackingStartsAt}}): {{trackingUrl}}'
 WHERE event_type = 'trip.reminder.4h' AND channel = 'sms' AND body = 'Boarding in 4h — PNR {{pnr}}, {{boardingAt}}. Pickup: {{pickup.stopName}} ({{pickup.landmark}}). Bus {{busNumber}}. Driver(s): {{driversList}}. Crew: {{attendantsList}}. Track (live from {{trackingStartsAt}}): {{trackingUrl}}';
UPDATE notification_templates SET body = 'Your bus boards in 4 hours! *{{pnr}}*' || E'\n' || '' || E'\n' || '📍 Pickup: *{{pickup.stopName}}*, {{boardingAt}}' || E'\n' || '{{pickup.landmark}}' || E'\n' || '{{pickup.address}}' || E'\n' || '' || E'\n' || '🚌 Bus number: *{{busNumber}}*' || E'\n' || '💺 Seat(s): *{{seats}}*' || E'\n' || '👨‍✈️ Driver(s): {{driversList}}' || E'\n' || '🧑‍💼 Conductor / attendant(s): {{attendantsList}}' || E'\n' || '' || E'\n' || '📍 Track your bus: {{trackingUrl}}' || E'\n' || '(The bus shows on the map from {{trackingStartsAt}}.)' || E'\n' || '' || E'\n' || 'Please reach 15 minutes early.'
 WHERE event_type = 'trip.reminder.4h' AND channel = 'whatsapp' AND body = 'Your bus boards in 4 hours! *{{pnr}}*' || E'\n' || '' || E'\n' || '📍 Pickup: *{{pickup.stopName}}*, {{boardingAt}}' || E'\n' || '{{pickup.landmark}}' || E'\n' || '{{pickup.address}}' || E'\n' || '' || E'\n' || '🚌 Bus number: *{{busNumber}}*' || E'\n' || '👨‍✈️ Driver(s): {{driversList}}' || E'\n' || '🧑‍💼 Conductor / attendant(s): {{attendantsList}}' || E'\n' || '' || E'\n' || '📍 Track your bus: {{trackingUrl}}' || E'\n' || '(The bus shows on the map from {{trackingStartsAt}}.)' || E'\n' || '' || E'\n' || 'Please reach 15 minutes early.';
UPDATE notification_templates SET body = 'Your bus boards in 4 hours, at {{boardingAt}}.' || E'\n' || '' || E'\n' || 'Pickup point: {{pickup.stopName}}' || E'\n' || 'Landmark: {{pickup.landmark}}' || E'\n' || 'Address: {{pickup.address}}' || E'\n' || '' || E'\n' || 'Bus number: {{busNumber}}' || E'\n' || 'Seat(s): {{seats}}' || E'\n' || 'Your crew:' || E'\n' || '{{crewList}}' || E'\n' || '' || E'\n' || 'Track your bus: {{trackingUrl}}' || E'\n' || 'The bus shows on the map from {{trackingStartsAt}}, one hour before departure.' || E'\n' || '' || E'\n' || 'Please reach your pickup point 15 minutes early.'
 WHERE event_type = 'trip.reminder.4h' AND channel = 'email' AND body = 'Your bus boards in 4 hours, at {{boardingAt}}.' || E'\n' || '' || E'\n' || 'Pickup point: {{pickup.stopName}}' || E'\n' || 'Landmark: {{pickup.landmark}}' || E'\n' || 'Address: {{pickup.address}}' || E'\n' || '' || E'\n' || 'Bus number: {{busNumber}}' || E'\n' || 'Your crew:' || E'\n' || '{{crewList}}' || E'\n' || '' || E'\n' || 'Track your bus: {{trackingUrl}}' || E'\n' || 'The bus shows on the map from {{trackingStartsAt}}, one hour before departure.' || E'\n' || '' || E'\n' || 'Please reach your pickup point 15 minutes early.';
UPDATE notification_templates SET body = 'Last reminder: PNR {{pnr}} boards at {{boardingAt}} from {{pickup.stopName}}. Bus {{busNumber}}, seat(s) {{seats}}. Driver(s): {{driversList}}. Crew: {{attendantsList}}. Track live now: {{trackingUrl}}'
 WHERE event_type = 'trip.reminder.1h' AND channel = 'sms' AND body = 'Last reminder: PNR {{pnr}} boards at {{boardingAt}} from {{pickup.stopName}}. Bus {{busNumber}}. Driver(s): {{driversList}}. Crew: {{attendantsList}}. Track live now: {{trackingUrl}}';
UPDATE notification_templates SET body = 'Last reminder — your bus boards in 1 hour! *{{pnr}}*' || E'\n' || '' || E'\n' || '📍 Pickup: *{{pickup.stopName}}*, {{boardingAt}}' || E'\n' || '{{pickup.landmark}}' || E'\n' || '' || E'\n' || '🚌 Bus number: *{{busNumber}}*' || E'\n' || '💺 Seat(s): *{{seats}}*' || E'\n' || '👨‍✈️ Driver(s): {{driversList}}' || E'\n' || '🧑‍💼 Conductor / attendant(s): {{attendantsList}}' || E'\n' || '' || E'\n' || '📍 Your bus is live now: {{trackingUrl}}' || E'\n' || '' || E'\n' || 'Please be at the pickup point 15 minutes early.'
 WHERE event_type = 'trip.reminder.1h' AND channel = 'whatsapp' AND body = 'Last reminder — your bus boards in 1 hour! *{{pnr}}*' || E'\n' || '' || E'\n' || '📍 Pickup: *{{pickup.stopName}}*, {{boardingAt}}' || E'\n' || '{{pickup.landmark}}' || E'\n' || '' || E'\n' || '🚌 Bus number: *{{busNumber}}*' || E'\n' || '👨‍✈️ Driver(s): {{driversList}}' || E'\n' || '🧑‍💼 Conductor / attendant(s): {{attendantsList}}' || E'\n' || '' || E'\n' || '📍 Your bus is live now: {{trackingUrl}}' || E'\n' || '' || E'\n' || 'Please be at the pickup point 15 minutes early.';
UPDATE notification_templates SET body = 'Your bus boards in 1 hour, at {{boardingAt}}.' || E'\n' || '' || E'\n' || 'Pickup point: {{pickup.stopName}}' || E'\n' || 'Landmark: {{pickup.landmark}}' || E'\n' || 'Address: {{pickup.address}}' || E'\n' || '' || E'\n' || 'Bus number: {{busNumber}}' || E'\n' || 'Seat(s): {{seats}}' || E'\n' || 'Your crew:' || E'\n' || '{{crewList}}' || E'\n' || '' || E'\n' || 'Your bus is live on the map now: {{trackingUrl}}' || E'\n' || '' || E'\n' || 'Please be at your pickup point 15 minutes early.'
 WHERE event_type = 'trip.reminder.1h' AND channel = 'email' AND body = 'Your bus boards in 1 hour, at {{boardingAt}}.' || E'\n' || '' || E'\n' || 'Pickup point: {{pickup.stopName}}' || E'\n' || 'Landmark: {{pickup.landmark}}' || E'\n' || 'Address: {{pickup.address}}' || E'\n' || '' || E'\n' || 'Bus number: {{busNumber}}' || E'\n' || 'Your crew:' || E'\n' || '{{crewList}}' || E'\n' || '' || E'\n' || 'Your bus is live on the map now: {{trackingUrl}}' || E'\n' || '' || E'\n' || 'Please be at your pickup point 15 minutes early.';

-- migrate:down

SELECT 1;
