/**
 * Central catalogue of machine-readable error codes.
 *
 * RULES
 *  - A code is a permanent public API contract. Never rename or reuse one.
 *  - Format: `DOMAIN.SPECIFIC_CONDITION`, SCREAMING_SNAKE after the dot.
 *  - Every code maps to exactly one HTTP status (see `errors.ts`).
 *  - Clients branch on `code`, never on `message`. Messages are for humans and
 *    are free to change / be localised.
 */
export const ErrorCode = {
  // ── Generic / transport ────────────────────────────────────────────────
  COMMON_INTERNAL: 'COMMON.INTERNAL_ERROR',
  COMMON_VALIDATION: 'COMMON.VALIDATION_FAILED',
  COMMON_NOT_FOUND: 'COMMON.NOT_FOUND',
  COMMON_CONFLICT: 'COMMON.CONFLICT',
  COMMON_UNAUTHENTICATED: 'COMMON.UNAUTHENTICATED',
  COMMON_FORBIDDEN: 'COMMON.FORBIDDEN',
  COMMON_RATE_LIMITED: 'COMMON.RATE_LIMITED',
  COMMON_TIMEOUT: 'COMMON.TIMEOUT',
  COMMON_UNAVAILABLE: 'COMMON.SERVICE_UNAVAILABLE',
  COMMON_PAYLOAD_TOO_LARGE: 'COMMON.PAYLOAD_TOO_LARGE',
  COMMON_UNSUPPORTED_MEDIA: 'COMMON.UNSUPPORTED_MEDIA_TYPE',
  COMMON_PRECONDITION_FAILED: 'COMMON.PRECONDITION_FAILED',
  COMMON_DEPENDENCY_FAILED: 'COMMON.UPSTREAM_DEPENDENCY_FAILED',

  // ── Idempotency ────────────────────────────────────────────────────────
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY.KEY_REQUIRED',
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY.REQUEST_IN_PROGRESS',
  IDEMPOTENCY_PAYLOAD_MISMATCH: 'IDEMPOTENCY.PAYLOAD_MISMATCH',

  // ── Persistence ────────────────────────────────────────────────────────
  DB_UNIQUE_VIOLATION: 'DB.UNIQUE_VIOLATION',
  DB_FOREIGN_KEY_VIOLATION: 'DB.FOREIGN_KEY_VIOLATION',
  DB_CHECK_VIOLATION: 'DB.CHECK_VIOLATION',
  DB_SERIALIZATION_FAILURE: 'DB.SERIALIZATION_FAILURE',
  DB_DEADLOCK: 'DB.DEADLOCK_DETECTED',
  DB_LOCK_TIMEOUT: 'DB.LOCK_TIMEOUT',
  DB_STATEMENT_TIMEOUT: 'DB.STATEMENT_TIMEOUT',
  DB_OPTIMISTIC_LOCK: 'DB.OPTIMISTIC_LOCK_FAILED',
  DB_VIEW_NOT_READY: 'DB.VIEW_NOT_READY',

  // B2B agent network
  AGENT_NOT_ACTIVE: 'AGENT.NOT_ACTIVE',
  AGENT_INSUFFICIENT_FUNDS: 'AGENT.INSUFFICIENT_FUNDS',

  // ── Tenancy & identity (Part 2) ────────────────────────────────────────
  TENANT_NOT_RESOLVED: 'TENANT.NOT_RESOLVED',
  TENANT_SUSPENDED: 'TENANT.SUSPENDED',
  TENANT_QUOTA_EXCEEDED: 'TENANT.QUOTA_EXCEEDED',
  TENANT_FEATURE_DISABLED: 'TENANT.FEATURE_DISABLED',
  AUTH_INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH.TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH.TOKEN_INVALID',
  AUTH_SESSION_REVOKED: 'AUTH.SESSION_REVOKED',
  AUTH_MFA_REQUIRED: 'AUTH.MFA_REQUIRED',
  AUTH_OTP_INVALID: 'AUTH.OTP_INVALID',
  AUTH_ACCOUNT_LOCKED: 'AUTH.ACCOUNT_LOCKED',

  // ── Inventory (Part 5) ─────────────────────────────────────────────────
  INVENTORY_SEAT_UNAVAILABLE: 'INVENTORY.SEAT_UNAVAILABLE',
  INVENTORY_HOLD_EXPIRED: 'INVENTORY.HOLD_EXPIRED',
  INVENTORY_TRIP_CLOSED: 'INVENTORY.TRIP_CLOSED',
  INVENTORY_TRIP_CANCELLED: 'INVENTORY.TRIP_CANCELLED',
  INVENTORY_SEGMENT_INVALID: 'INVENTORY.SEGMENT_INVALID',

  // ── Pricing (Part 6) ───────────────────────────────────────────────────
  PRICING_NO_FARE_DEFINED: 'PRICING.NO_FARE_DEFINED',
  PRICING_QUOTE_EXPIRED: 'PRICING.QUOTE_EXPIRED',
  PRICING_COUPON_INVALID: 'PRICING.COUPON_INVALID',

  // ── Booking (Part 7) ───────────────────────────────────────────────────
  BOOKING_INVALID_STATE: 'BOOKING.INVALID_STATE_TRANSITION',
  BOOKING_ALREADY_CANCELLED: 'BOOKING.ALREADY_CANCELLED',
  BOOKING_NOT_CANCELLABLE: 'BOOKING.NOT_CANCELLABLE',
  BOOKING_DEPARTED: 'BOOKING.TRIP_ALREADY_DEPARTED',

  // ── Payments (Part 8) ──────────────────────────────────────────────────
  PAYMENT_DECLINED: 'PAYMENT.DECLINED',
  PAYMENT_GATEWAY_ERROR: 'PAYMENT.GATEWAY_ERROR',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT.AMOUNT_MISMATCH',
  PAYMENT_ALREADY_CAPTURED: 'PAYMENT.ALREADY_CAPTURED',
  REFUND_NOT_ALLOWED: 'REFUND.NOT_ALLOWED',
  REFUND_NOT_FOUND: 'REFUND.NOT_FOUND',
  REFUND_ALREADY_EXISTS: 'REFUND.ALREADY_EXISTS',
  LEDGER_UNBALANCED: 'LEDGER.UNBALANCED_ENTRY',

  // ── Departure control & invoicing (Part 13) ────────────────────────────
  DCS_ALREADY_CHARTED: 'DCS.ALREADY_CHARTED',
  DCS_TRIP_NOT_FOUND: 'DCS.TRIP_NOT_FOUND',
  INVOICE_ALREADY_ISSUED: 'INVOICE.ALREADY_ISSUED',

  // ── Storefront (Part 14) ───────────────────────────────────────────────
  REVIEW_NOT_ELIGIBLE: 'REVIEW.NOT_ELIGIBLE',
  REVIEW_ALREADY_EXISTS: 'REVIEW.ALREADY_EXISTS',
  REVIEW_INVALID_RATING: 'REVIEW.INVALID_RATING',
  SUPPORT_TICKET_CLOSED: 'SUPPORT.TICKET_CLOSED',
  SUPPORT_INVALID_TRANSITION: 'SUPPORT.INVALID_TRANSITION',
  OFFER_INVALID_WINDOW: 'OFFER.INVALID_WINDOW',
  CONNECTION_INVALID_LAYOVER: 'CONNECTION.INVALID_LAYOVER',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
